# Generated by fusen: do not edit by hand

#' my_fun A function to read all available excel files in a folder
#'
#' @param folder A path to a folder (type = character)
#'
#' @importFrom purrr possibly map
#' @importFrom readxl read_excel
#' @return A list of data frames, after reading all available excel files in a folder
#' @export

#' @examples
#' multi_read_excel(folder = "inst/")
multi_read_excel <- function(folder = "data/"){
  
  files <- list.files(folder, full.names = TRUE, pattern = '[.]xlsx$')
  filenames <- list.files(folder, pattern = '[.]xlsx$')
  data <- files %>%
    map(possi_excel)
  names(data) <- filenames

  return(data)
    
}

