# Generated by fusen: do not edit by hand

#' my_fun A function to read an excel file and return NULL if there is a problem with the file
#'
#' @param A filename or pathfile (type = character)
#'
#' @importFrom purrr possibly
#' @importFrom readxl read_excel
#' @return A data frame when the file is read successfully, or NULL if there is an error
#' @export

possi_excel <- possibly(read_excel, otherwise = NULL, quiet = TRUE)

